name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build -c production
      - run: npm run format:check
      - run: npm run lint
      - run: npm test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
